services:
  - type: web
    name: tech-hub
    runtime: static
    repo: https://github.com/WHS-DTECH/TECH-HUB
    branch: main
    buildCommand: echo "No build step required"
    staticPublishPath: .
